import axios from "axios";
import { useRouter } from "next/dist/client/router";
import Head from "next/head";
import { useEffect, useState } from "react";
import EditExamForm from "../components/EditExamForm";
import Footer from "../components/Footer";
import Header from "../components/Header";

// Done form: question-answer-rightAnswer - 14-10-2021

export default function EditExam() {
	const router = useRouter();
	const [exam, setExam] = useState([]);
	useEffect(() => {
		const fetchExam = async () => {
			try {
				const id = router.query.idExam;

				const url = `${process.env.NEXT_PUBLIC_API_URL}/exams/${id}/update`;
				//const token = localStorage.getItem("REFRESH_TOKEN");
				const res = await axios.get(url, {
					headers: {
						access_token: localStorage.getItem("REFRESH_TOKEN"),
					},
				});

				if (res.data) setExam(res.data);
			} catch (error) {
				console.log("Failed to fetch exam:", error);
			}
		};
		fetchExam();
	}, [router.query.idExam]);

	return (
		<div className="w-auto">
			<Head>
				<title>Exam</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<div className="p-5">
				<EditExamForm exam={exam} />
			</div>
			<Footer />
		</div>
	);
}
