import axios from "axios";
import Head from "next/head";
import { useEffect, useState } from "react";
import BodyExam from "../components/BodyExam";
import Footer from "../components/Footer";
import Header from "../components/Header";
import StateBox from "../components/StateBox";
import examApi from "./api/examApi";

// Done form: question-answer-rightAnswer - 14-10-2021
// Done form: auto submit when timeout - 19-10-2021

export default function TakeExam({ exam }) {
	const [timeout, setTimeout] = useState(false);

	return (
		<div>
			<Head>
				<title>Do the Exam</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header disable={true} />
			<div className="flex justify-between my-10 flex-col md:flex-row">
				<StateBox timeout={timeout} setTimeout={setTimeout} />
				<BodyExam timeout={timeout} exam={exam} />
			</div>
			<Footer disable={true} />
		</div>
	);
}

export async function getServerSideProps(context) {
	const params = context.query;

	const url = `${process.env.NEXT_PUBLIC_API_URL}/exams/${params.idExam}/take`;
	const res = await axios.get(url);

	return {
		props: {
			exam: res.data,
		},
	};
}
