import axios from "axios";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { useDispatch } from "react-redux";
import BodyExam from "../components/BodyExam";
import Footer from "../components/Footer";
import Header from "../components/Header";
import StateBox from "../components/StateBox";
import { initTime } from "../store/slices/timeSlice";
import examApi from "./api/examApi";

// Done form: question-answer-rightAnswer - 14-10-2021
// Done form: auto submit when timeout - 19-10-2021

export default function TakeExam() {
	const router = useRouter();
	const dispatch = useDispatch();

	const [timeout, setTimeout] = useState(false);
	const [exam, setExam] = useState({});

	//Fetch dữ liệu
	useEffect(() => {
		const fetchExam = async () => {
			try {
				const url = `${process.env.NEXT_PUBLIC_API_URL}/exams/${router.query.idExam}/take`;
				const token = localStorage.getItem("REFRESH_TOKEN");
				const res = await axios.get(url, {
					headers: {
						access_token: token,
					},
				});
				dispatch(initTime(res.data.minuteLimit));
				setExam(res.data);
			} catch (error) {
				console.log("Failed to fetch exam:", error);
			}
		};
		fetchExam();
	}, [router.query.idExam]);

	return (
		<div>
			<Head>
				<title>Do the Exam</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header disable={true} />
			<div className="flex justify-between my-10 flex-col md:flex-row">
				<BodyExam exam={exam} />
				<StateBox />
			</div>
			<Footer disable={true} />
		</div>
	);
}
