import Head from "next/head";
import { useState } from "react";
import BodyExam from "../components/BodyExam";
import StateBox from "../components/StateBox";

// Done form: question-answer-rightAnswer - 14-10-2021
// Done form: auto submit when timeout - 19-10-2021

export default function MakeExam() {
	const [timeout, setTimeout] = useState(false);

	return (
		<div className="flex">
			<Head>
				<title>Do the Exam</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<BodyExam timeout={timeout} />
			<StateBox timeout={timeout} setTimeout={setTimeout} />
		</div>
	);
}
