import Footer from "../components/Footer";
import Header from "../components/Header";
import Head from "next/head";

export default function Admin() {
	return (
		<div>
			<Head>
				<title>Exam Bank - DKG</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<div>ADMIN</div>
			<Footer />
		</div>
	);
}
