import { useRouter } from "next/dist/client/router";
import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";
import axios from "axios";
import { useEffect, useState } from "react";

// Done form: question-answer-rightAnswer - 14-10-2021

export default function Exam() {
	const router = useRouter();

	const [exams, setExams] = useState([]);

	// Fetch dữ liệu
	useEffect(() => {
		const fetchExam = async () => {
			try {
				const url = `http://localhost:5000/exams?subject=${router.query.subject}`;
				const res = await axios.get(url);

				setExams(res.data);
			} catch (error) {
				console.log("Failed to fetch exam:", error);
			}
		};
		fetchExam();
	}, []);

	const handleDeleteExam = async (id) => {
		const index = exams.findIndex((e) => e._id == id);
		console.log(index);
		console.log(exams);
		try {
			const url = `http://localhost:5000/admin/exams/${id}/delete`;
			const res = await axios.delete(url);

			if (res.data.message == "Success") {
				console.log("delete Success");
				setExams([...exams.slice(0, index), ...exams.slice(index + 1)]);
			}
		} catch (error) {
			console.log("Failed to fetch exam:", error);
		}
	};
	return (
		<div>
			<Head>
				<title>Exam</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />

			<section className="flex py-5 px-5">
				<div className="flex-1 py-10 px-20 ">
					<div className="w-4/5  bg-gray-200 bg-opacity-40 p-10 shadow-md">
						<div className="flex justify-between">
							<h1 className="text-3xl font-bold text-green-800 mb-3">
								Đề thi theo môn học
							</h1>
							<svg
								xmlns="http://www.w3.org/2000/svg"
								className="h-6 w-6"
								fill="none"
								viewBox="0 0 24 24"
								stroke="currentColor"
							>
								<path
									strokeLinecap="round"
									strokeLinejoin="round"
									strokeWidth={2}
									d="M3 4a1 1 0 011-1h16a1 1 0 011 1v2.586a1 1 0 01-.293.707l-6.414 6.414a1 1 0 00-.293.707V17l-4 4v-6.586a1 1 0 00-.293-.707L3.293 7.293A1 1 0 013 6.586V4z"
								/>
							</svg>
						</div>
						{exams.length == 0 && (
							<h1>Chưa có đề thi của môn {router.query.subject}</h1>
						)}
						{exams.map((e) => (
							<div className="py-3 border-b-2">
								<div className="flex jutify-between items-center">
									<div className="flex flex-1 jutify-between items-center">
										<svg
											xmlns="http://www.w3.org/2000/svg"
											className="h-6 w-6"
											fill="none"
											viewBox="0 0 24 24"
											stroke="currentColor"
										>
											<path
												strokeLinecap="round"
												strokeLinejoin="round"
												strokeWidth={2}
												d="M15.172 7l-6.586 6.586a2 2 0 102.828 2.828l6.414-6.586a4 4 0 00-5.656-5.656l-6.415 6.585a6 6 0 108.486 8.486L20.5 13"
											/>
										</svg>

										<h3
											className="text-yellow-500 text-2xl font-semibold ml-2 cursor-pointer"
											onClick={() =>
												router.push({
													pathname: "takeExam",
													query: {
														idExam: e._id,
													},
												})
											}
										>
											{e.name}
										</h3>
									</div>

									{/* <svg
												xmlns="http://www.w3.org/2000/svg"
												className="h-6 w-6"
												fill="none"
												viewBox="0 0 24 24"
												stroke="currentColor"
											>
												<path
													strokeLinecap="round"
													strokeLinejoin="round"
													strokeWidth={2}
													d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
												/>
											</svg> */}

									<svg
										xmlns="http://www.w3.org/2000/svg"
										className="h-6 w-6 cursor-pointer"
										fill="none"
										viewBox="0 0 24 24"
										stroke="currentColor"
										onClick={() => handleDeleteExam(e._id)}
									>
										<path
											strokeLinecap="round"
											strokeLinejoin="round"
											strokeWidth={2}
											d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"
										/>
									</svg>
								</div>
								<div className="ml-8 mt-2">
									<h3 className="text-md text-gray-600 font-semibold">
										Môn:
										<span className="text-yellow-500 ml-2">{e.subject}</span>
									</h3>
									<h4 className="text-md text-gray-600 font-semibold">
										Người đăng:
										<span className="text-yellow-500 ml-2">
											{e.creator.name}
										</span>
									</h4>
									<h4 className="text-md text-gray-600 font-semibold">
										Ngày đăng:
										<span className="text-yellow-500 ml-2">{e.openedAt}</span>
									</h4>
									<h4 className="text-md text-gray-600 font-semibold">
										Đã làm bài:
										<span className="text-yellow-500 ml-2">
											{e.attemptLimit}
										</span>
									</h4>
								</div>
							</div>
						))}
					</div>
				</div>

				<div className="border-l-2 border-gray-200 pl-10 pr-3 grid place-content-center mb-10">
					<h1 className="text-2xl font-bold text-green-800 mb-3">
						Đề thi theo môn học
					</h1>
					<div className="grid grid-cols-1 gap-3 place-items-center">
						<div
							className="border border-gray-300 cursor-pointer"
							onClick={() =>
								router.push({
									pathname: "exam",
									query: {
										subject: "math",
									},
								})
							}
						>
							<img
								className="object-cover w-64 h-16"
								src="/img/math.jpg"
								alt="math"
							/>
							<h3 className="text-center w-full py-1 text-md ">Toán</h3>
						</div>
						<div
							className="border border-gray-300 cursor-pointer"
							onClick={() =>
								router.push({
									pathname: "exam",
									query: {
										subject: "english",
									},
								})
							}
						>
							<img
								className="object-cover w-64 h-16"
								src="/img/english.jpg"
								alt="english"
							/>
							<h3 className="text-center w-full py-1 text-md ">Tiếng Anh</h3>
						</div>
						<div
							className="border border-gray-300 cursor-pointer"
							onClick={() =>
								router.push({
									pathname: "exam",
									query: {
										subject: "physics",
									},
								})
							}
						>
							<img
								className="object-cover w-64 h-16"
								src="/img/physics.jpg"
								alt="physics"
							/>
							<h3 className="text-center w-full py-1 text-md ">Vật Lý</h3>
						</div>
						<div
							className="border border-gray-300 cursor-pointer"
							onClick={() =>
								router.push({
									pathname: "exam",
									query: {
										subject: "chemistry",
									},
								})
							}
						>
							<img
								className="object-cover w-64 h-16"
								src="/img/chemistry.jpg"
								alt="chemistry"
							/>
							<h3 className="text-center w-full py-1 text-md ">Hóa Học</h3>
						</div>
						<div
							className="border border-gray-300 cursor-pointer"
							onClick={() =>
								router.push({
									pathname: "exam",
									query: {
										subject: "biology",
									},
								})
							}
						>
							<img
								className="object-cover w-64 h-16"
								src="/img/biology.jpg"
								alt="biology"
							/>
							<h3 className="text-center w-full py-1 text-md ">Sinh Học</h3>
						</div>
						<div
							className="border border-gray-300 cursor-pointer"
							onClick={() =>
								router.push({
									pathname: "exam",
									query: {
										subject: "history",
									},
								})
							}
						>
							<img
								className="object-cover w-64 h-16"
								src="/img/history.jpg"
								alt="history"
							/>
							<h3 className="text-center w-full py-1 text-md ">Lịch Sử</h3>
						</div>
						<div
							className="border border-gray-300 cursor-pointer"
							onClick={() =>
								router.push({
									pathname: "exam",
									query: {
										subject: "geography",
									},
								})
							}
						>
							<img
								className="object-cover w-64 h-16"
								src="/img/geography.jpg"
								alt="geography"
							/>
							<h3 className="text-center w-full py-1 text-md">Địa Lý</h3>
						</div>

						<div
							className="border border-gray-300 cursor-pointer"
							onClick={() =>
								router.push({
									pathname: "exam",
									query: {
										subject: "civicEducation",
									},
								})
							}
						>
							<img
								className="object-cover w-64 h-16"
								src="/img/civiceducation.jpg"
								alt="civic education"
							/>
							<h3 className="text-center w-full py-1 text-md ">
								Giáo Dục Công Dân
							</h3>
						</div>
					</div>
				</div>
			</section>

			<Footer />
		</div>
	);
}

// export const getStaticProps = async () => {
// 	try {
// 		const url = "http://localhost:5000/admin/users";
// 		const res = await axios.get(url);
// 		console.log("res", res.data);

// 		return {
// 			props: {
// 				exam: res.data,
// 			},
// 		};
// 	} catch (error) {
// 		console.log("Failed to fetch exam:", error);
// 	}

// 	return {
// 		props: {},
// 	};
// };
