import { useRouter } from "next/dist/client/router";
import Head from "next/head";

// Done form: question-answer-rightAnswer - 14-10-2021

export default function Home() {
	const router = useRouter();

	return (
		<div className="flex">
			<Head>
				<title>Do Exam</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<button onClick={() => router.push("/makeExam")}>Làm Đề</button>
		</div>
	);
}
