import { useRouter } from "next/router";
import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";

// Done form: question-answer-rightAnswer - 14-10-2021

export default function Home() {
	const router = useRouter();

	return (
		<div>
			<Head>
				<title>Exam Bank - DKG</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<section className="bg-home h-[918px] bg-cover flex justify-center items-center">
				<div className="w-1/2 text-center justify-center bg-gray-100 bg-opacity-60 py-10 rounded-3xl shadow-lg">
					<h1 className="text-[60px] text-red-500 font-bold ">
						LUYỆN THI ĐẠI HỌC
					</h1>
					<p className="text-gray-700 text-lg font-medium px-32">
						Đây là những giờ phút vô cùng quan trọng của cuộc đời, hãy tập trung
						ôn thi và đừng để bất cứ điều gì làm xao nhãng bạn nhé.
					</p>
					<button
						className="border-4 border-red-500 mt-10 text-red-600 text-xl font-bold rounded-full px-10 py-2 relative before:absolute before:top-0 before:left-0 before:w-full before:h-full before:border-2 before:border-transparent before:rounded-full before:tranform hover:before:scale-x-110 hover:before:scale-y-150
                        before:transition before:ease-out hover:before:border-red-400"
					>
						Tham gia miễn phí
					</button>
				</div>
			</section>

			<div className="grid place-content-center my-10">
				<h1 className="text-3xl font-bold text-green-800 mb-3">
					Đề thi theo môn học
				</h1>
				<div className="grid grid-cols-2 gap-3 place-items-center">
					<div
						className="border border-gray-300 cursor-pointer"
						onClick={() =>
							router.push({
								pathname: "exam",
								query: {
									page: "math",
								},
							})
						}
					>
						<img
							className="object-cover w-96 h-48"
							src="/img/math.jpg"
							alt="math"
						/>
						<h3 className="text-center w-full py-3 text-xl ">Toán</h3>
					</div>
					<div
						className="border border-gray-300 cursor-pointer"
						onClick={() =>
							router.push({
								pathname: "exam",
								query: {
									page: "english",
								},
							})
						}
					>
						<img
							className="object-cover w-96 h-48"
							src="/img/english.jpg"
							alt="english"
						/>
						<h3 className="text-center w-full py-3 text-xl ">Tiếng Anh</h3>
					</div>
					<div
						className="border border-gray-300 cursor-pointer"
						onClick={() =>
							router.push({
								pathname: "exam",
								query: {
									page: "history",
								},
							})
						}
					>
						<img
							className="object-cover w-96 h-48"
							src="/img/history.jpg"
							alt="history"
						/>
						<h3 className="text-center w-full py-3 text-xl ">Lịch Sử</h3>
					</div>
					<div
						className="border border-gray-300 cursor-pointer"
						onClick={() =>
							router.push({
								pathname: "exam",
								query: {
									page: "geography",
								},
							})
						}
					>
						<img
							className="object-cover w-96 h-48"
							src="/img/geography.jpg"
							alt="geography"
						/>
						<h3 className="text-center w-full py-3 text-xl">Địa Lý</h3>
					</div>
					<div
						className="border border-gray-300 cursor-pointer"
						onClick={() =>
							router.push({
								pathname: "exam",
								query: {
									page: "physics",
								},
							})
						}
					>
						<img
							className="object-cover w-96 h-48"
							src="/img/physics.jpg"
							alt="physics"
						/>
						<h3 className="text-center w-full py-3 text-xl ">Vật Lý</h3>
					</div>
					<div
						className="border border-gray-300 cursor-pointer"
						onClick={() =>
							router.push({
								pathname: "exam",
								query: {
									page: "chemistry",
								},
							})
						}
					>
						<img
							className="object-cover w-96 h-48"
							src="/img/chemistry.jpg"
							alt="chemistry"
						/>
						<h3 className="text-center w-full py-3 text-xl ">Hóa Học</h3>
					</div>
					<div
						className="border border-gray-300 cursor-pointer"
						onClick={() =>
							router.push({
								pathname: "exam",
								query: {
									page: "biology",
								},
							})
						}
					>
						<img
							className="object-cover w-96 h-48"
							src="/img/biology.jpg"
							alt="biology"
						/>
						<h3 className="text-center w-full py-3 text-xl ">Sinh Học</h3>
					</div>
					<div
						className="border border-gray-300 cursor-pointer"
						onClick={() =>
							router.push({
								pathname: "exam",
								query: {
									page: "civicEducation",
								},
							})
						}
					>
						<img
							className="object-cover w-96 h-48"
							src="/img/civiceducation.jpg"
							alt="civic education"
						/>
						<h3 className="text-center w-full py-3 text-xl ">
							Giáo Dục Công Dân
						</h3>
					</div>
				</div>
			</div>
			<Footer />
		</div>
	);
}
