import Head from "next/head";
import { useState } from "react";
import BodyExam from "../components/BodyExam";
import Footer from "../components/Footer";
import Header from "../components/Header";
import StateBox from "../components/StateBox";

// Done form: question-answer-rightAnswer - 14-10-2021
// Done form: auto submit when timeout - 19-10-2021

export default function TakeExam() {
	const [timeout, setTimeout] = useState(false);

	return (
		<div>
			<Head>
				<title>Do the Exam</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header disable={true} />
			<div className="flex justify-between my-10">
				<BodyExam timeout={timeout} />
				{/* <StateBox timeout={timeout} setTimeout={setTimeout} /> */}
			</div>
			<Footer disable={true} />
		</div>
	);
}
